all : multi-utility-calc.o
	gcc multi-utility-calc.o -o multi-utility-calc

multi-utility-calc.o : multi-utility-calc.c
	gcc -c multi-utility-calc.c -o multi-utility-calc.o

clean : 
	rm multi-utility-calc.o multi-utility-calc