all : function-menu-calc.o
	gcc function-menu-calc.o -o function-menu-calc

function-menu-calc.o : function-menu-calc.c
	gcc -c function-menu-calc.c -o function-menu-calc.o

clean :
	rm function-menu-calc.o function-menu-calc